### ISSUE TITLE
I am very eager for you to release the latest official version

### ISSUE THREAD

**Issue by hl0709** [juancamejoalarcon/paper-tinymce#7]
Hello, I downloaded npm install paper tinymce, but it is not the latest. After compiling the latest paper tinymce main that I manually downloaded, an error was reported in my own JavaScript file. I am very eager to download it

**Comment by juancamejoalarcon** [comment]
Hi @hl0709 

I am changing the perspective of this project. 
I have removed the plugin, it is a bit complex to make it compatible with the rest of Tinymce plugins.
Right now I'm doing a full editor rendering on a shadow DOM.
I have changed the README instructions and removed the npm package until I can release a stable version.
The only thing l can give now are the scripts: https://github.com/juancamejoalarcon/paper-tinymce/blob/main/paper-tinymce.js o https://github.com/juancamejoalarcon/paper-tinymce/blob/main/paper-tinymce.umd.js
Use the PaperTinymce('#editor-container-id') function which will return an extended Tinymce instance with a number of methods I have added to it.
Take a look at https://github.com/juancamejoalarcon/paper-tinymce/blob/main/src/core/paper-instance.ts
